---
- name: prepare host network configuration
  hosts: cdpcm
  become: true

  tasks:
  - name: copy /etc/hosts with privates addresses to host
    copy:
      src: network/local_hosts
      dest: /etc/hosts
      backup: yes
  - name: print the private name
    debug:
      msg: "{{ hostvars[inventory_hostname].private_name }}"
  - name: set a pivate network hostname for the host
    hostname:
      name: "{{ hostvars[inventory_hostname].private_name }}"
  - name: save host iptable.
    shell: iptables-save > ~/firewall.rules 
  - name: stop firewall service
    service:
      name: firewalld
      state: stopped
      enabled: no

