---
- name: POSTGRES installation and configuration
  hosts: cdpcm
  become: true  

  tasks:
  - name: install postgres repository
    yum_repository: 
      name: pgdg11
      description: PostgreSQL 12 for RHEL/CentOS $releasever - $basearch
      file: pgdg-redhat-all  
      baseurl: "{{ postgres_repository }}"
      repo_gpgcheck: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG
      enabled: yes

  - name: install postgres common repository
    yum_repository:
      name: pgdg-common
      description: PostgreSQL common RPMs for RHEL/CentOS $releasever - $basearch
      file: pgdg-redhat-all
      baseurl: "{{ postgres_common }}"
      repo_gpgcheck: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG
      enabled: yes

  - name: install postgres sofware
    yum:
      name: 
        - postgresql{{ postgres_version }}-server
        - postgresql{{ postgres_version }}-contrib
        - repmgr
        - pg_stat_kcache
        - pg_stat_monitor
        - pg_qualstats
      state: present