---
- name: NETWORK - host network configuration
  hosts: cdpcluster
  become: true

  tasks:
  - name: get the service facts
    service_facts:
  
  - name: copy /etc/hosts with privates addresses to host
    copy:
      src: ../../files/local_hosts
      dest: /etc/hosts
      backup: yes
    tags: hosts
  
  - name: print the private name
    debug:
      msg: "{{ hostvars[inventory_hostname].private_name }}"
  
  - name: set a pivate network hostname for the host
    hostname:
      name: "{{ hostvars[inventory_hostname].private_name }}"
  
  - name: save host iptable.
    shell: iptables-save > ~/firewall.rules 
  
  - name: stop firewall service
    service:
      name: firewalld
      state: stopped
      enabled: no
    when: ansible_facts.services["firewalld.service"] is defined
  
  - name: stop iptables service if exists
    service:
      name: iptables
      state: stopped
      enabled: no
    when: ansible_facts.services["iptables.service"] is defined and ansible_facts.services["iptables.service"].state == 'enabled'
  
  - name: updade /etc/hostname
    lineinfile:
      path: /etc/sysconfig/network
      backup: yes
      regexp: '^HOSTNAME=.*'
      line: 'HOSTNAME={{ hostvars[inventory_hostname].private_name }}'
