---
- name: CLOUDERA MANAGER POST INSTALLATION 
  hosts: cdpcm
  become: true
  gather_facts: no

  environment:
    JAVA_HOME: "{{ java_home }}"
    PATH: "{{ java_home }}/bin:$PATH"

  tasks:
  - name: cm - configure certificated auto-tls
    command: /opt/cloudera/cm-agent/bin/certmanager setup --configure-services
    ignore_errors: yes
    
  - name: cm - install psycog
    yum:
      name: "{{ psycopg_package }}"
    tags: packages
  
  - name: cm - configure cloudera manager db
    become: true
    become_user: postgres    
    command: /opt/cloudera/cm/schema/scm_prepare_database.sh {{ cloudera_db_type }} scm scm {{ cdp_users_pass }}

  - name: cm - start cm service
    service:
      name: cloudera-scm-server
      state: started
      enabled: yes