---
- name: CLOUDERA MANAGER POST INSTALLATION 
  hosts: cdpcm
  become: true
  gather_facts: no

  environment:
    JAVA_HOME: "{{ java_home }}"
    PATH: "{{ java_home }}/bin:$PATH"

  tasks:
  - name: cm - configure certificated auto-tls
    command: /opt/cloudera/cm-agent/bin/certmanager setup --configure-services
    ignore_errors: yes
    
  - name: cm - install psycog
    yum:
      name: "{{ psycopg_package }}"
    tags: packages
  
  - name: cm - configure cloudera manager db 
    shell: /opt/cloudera/cm/schema/scm_prepare_database.sh -h localhost -P 5432   {{ cloudera_db_type }} scm scm '{{ cdp_users_pass }}'
    environment: 
      PATH: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
      SHELL: /bin/bash
     
  - name: cm - start cm service
    service:
      name: cloudera-scm-server
      state: started
      enabled: yes
    environment: 
      PATH: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin