---
- name: CLOUDERA MANAGER
  hosts: cdpcm
  become: true

  tasks:
  - name:
    yum:
      name:
        - cloudera-manager-daemons
        - cloudera-manager-agent
        - cloudera-manager-server
      state: present
      disable_gpg_check: yes
    tags: 
      - package
      - cloudera
