---
- name: REPOSITORIES
  hosts: cdpcluster
  become: true
  gather_facts: no

  tasks:
  - name: add cloudera repository
    yum_repository:
      name: cdp7
      description: cloudera cdp 7 repository
      file: cloudera-cdp7
      baseurl: "{{ cloudera_repo_url }}"
      gpgkey: "{{ cloudera_repo_url }}/RPM-GPG-KEY-cloudera"
      repo_gpgcheck: yes
      enabled: yes
    tags: repository